name: Github actions demo
on: push
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Prin the index.html page
        run: cat index.html

