name: Hello World
on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: echo "A demo build"
