name: Context Variables demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: use context Variables
        run: | 
           echo "The workflow is triggered by ${{github.actor}}"
           echo "The repository name is ${{github.repository}}"
           echo "The branch name is ${{github.ref_name}}"
      
      - name: Print all variables under github
        run: echo "${{ toJson(github) }}"

      - name: Print environment variables
        run: printenv
